services:
  webservicefactory:
    image: webservicefactory
    build:
      context: .
      dockerfile: WebServiceFactory/Dockerfile
    ports:
      - 8095:8080
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
        
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=111QQQwww
      - POSTGRES_USER=root
    ports:
      - 5433:5432
#    volumes:
#      - .:/docker-entrypoint-initdb.d
      
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080